general:
  agent_interaction_freq: 5
  algorithm: sac
  env: JSBSim-Heading2ControlTask-F16-v0
  flightgear: 'true'
  sim_frequency: 50
test:
  model: trained/September 18, 2022 - 07.14
train:
  model: none
  timesteps: 100000
