general:
  agent_interaction_freq: 5
  algorithm: sac
  env: JSBSim-Heading2ControlTask-F16-v0
  flightgear: 'true'
  sim_frequency: 50
test:
  mode: csv
  model: trained/March 15, 2022 - 22.47 - good
train:
  model: none
  timesteps: 100000
